basic1:
	python -m uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
basic2:
	python -m uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
app1:
	python -m uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
app2:
	python -m uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
app3:
	python -m uvicorn $@:app --host 0.0.0.0 --port 3000 --reload