build:
	docker build .
run:
	docker run -it --name centos centos:centos7 /bin/bash
exec:
	docker start centos
	docker attach centos
ps:
	docker ps -1
img:
	docker images
rm:
	docker rm centos
rmi:
	docker rmi centos:centos7
